(() => {
  const app=document.getElementById('app');
  const q=new URLSearchParams(location.search),view=q.get('screen')||'challenges';
  const A={hero:'/assets/mascot/chalote-hero-v1.webp',aqua:'/assets/challenges/aquaxp/chalote-aquaxp-v1.webp',rat:'/assets/challenges/rat-tech/chalote-rat-tech-v1.webp',reading:'/assets/challenges/reading/chalote-reading-v1.webp',offline:'/assets/challenges/screen-free/chalote-screen-free-v1.webp'};
  const logo=small=>`<div class="gti-brand ${small?'is-small':''}"><img src="/assets/ui/gti-missions-logo.svg" alt="GTI Missions"></div>`;
  const progress=(n,label='Progresso')=>`<div class="neon-progress" role="progressbar" aria-label="${label}"><i style="--value:${n}%"></i></div>`;
  const head=(icon,title,sub)=>`<header class="mission-screen-head"><button class="screen-back">‹</button><div><h1><span>${icon}</span>${title}</h1><p>${sub}</p></div><button class="screen-alert">♢</button></header>`;
  const nav=`<nav class="bottom-nav mission-bottom-nav"><a class="active"><span>⌂</span><small>Início</small></a><a><span>◇</span><small>Desafios</small></a><a><span>♜</span><small>Conquistas</small></a><a><span>♛</span><small>Ranking</small></a><a><span>♙</span><small>Perfil</small></a></nav>`;
  const shell=content=>`<main class="app-shell mission-app-shell">${content}</main>${nav}`;
  const stats=(a,b,c)=>`<section class="world-stat-grid"><div><span>🔥</span><b>${a}</b><small>dias seguidos</small></div><div><span>✦</span><b>${b}</b><small>progresso total</small></div><div><span>🏅</span><b>${c}</b><small>missões semana</small></div></section>`;
  const tile=(kind,img,eyebrow,title,desc,meta)=>`<a class="universe-tile ${kind}"><img src="${img}"><div class="universe-tile-shade"></div><div class="universe-tile-copy"><small>${eyebrow}</small><h2>${title}</h2><p>${desc}</p><span>${meta}</span></div></a>`;

  const screens={
    dashboard:()=>shell(`<div class="reference-home"><header class="home-brandbar"><button class="icon-only">☰</button>${logo(true)}<button class="icon-only">♢</button></header><section class="home-greeting"><div><h1>Olá, Explorador!</h1><p>Disciplina hoje, um amanhã extraordinário.</p></div></section><section class="compact-player-card"><div class="player-avatar-wrap"><span class="avatar">C</span><span>12</span></div><div><small>NÍVEL 12 • Explorador</small><b>2.450 / 3.000 XP</b>${progress(82)}</div><button>›</button></section><div class="compact-section-title"><h2>Meus desafios ativos</h2><button>Ver todos</button></div><section class="active-world-grid"><button class="active-world aqua"><span>💧</span><b>Água</b><small>12 dias</small></button><button class="active-world rat"><span>⚡</span><b>RAT Tech</b><small>2 treinos</small></button><button class="active-world reading"><span>📖</span><b>Leitura</b><small>8 dias</small></button><button class="active-world offline"><span>🌿</span><b>Sem Tela</b><small>5 dias</small></button></section><button class="overall-card"><div class="overall-ring" style="--overall:245deg"><span>68%</span></div><div><small>PROGRESSO GERAL</small><b>Suas missões desta semana</b><p>4 mundos ativos • ofensiva de 12 dias</p></div><i>›</i></button><section class="home-stat-row"><div><span>🔥</span><b>12</b><small>dias seguidos</small></div><div><span>♛</span><b>#6</b><small>ranking</small></div><div><span>✦</span><b>12</b><small>conquistas</small></div></section><button class="primary aurora-button full journey-button">Continuar minha jornada →</button></div>`),
    challenges:()=>shell(`<div class="challenge-select-screen"><header class="home-brandbar"><button class="icon-only">‹</button>${logo(true)}<button class="icon-only">♢</button></header><div class="select-intro"><h1>Escolha sua missão.</h1><p>Cada mundo transforma uma ação real em evolução.</p></div><section class="challenge-select-grid">${tile('aqua',A.aqua,'💧 HIDRATAÇÃO','AquaXP League','Mais saúde para ir mais longe.','1.250 ML HOJE')}${tile('rat',A.rat,'⚡ TREINO FÍSICO','RAT Tech','Força, movimento e consistência.','2/3 TREINOS')}${tile('reading',A.reading,'▣ CONHECIMENTO','Desafio da Leitura','Grandes mentes leem sempre.','3/5 DIAS')}${tile('offline',A.offline,'♧ VIDA REAL','Desafio Sem Tela','Mais presença. Mais vida.','COMEÇAR')}</section></div>`),
    reading:()=>shell(`<div class="world-screen reading-world-screen">${head('▣','Desafio da Leitura','Mais histórias. Grandes possibilidades.')}<section class="world-visual reading-visual"><img src="${A.reading}"><div class="world-visual-caption"><small>MINHA LEITURA ATUAL</small><b>O poder dos bons hábitos</b><span>120 / 280 páginas</span>${progress(43)}</div></section>${stats('8','120 pág.','3/5')}<blockquote>“Ler é viajar sem sair do lugar.”</blockquote><section class="world-progress-card"><div><small>META DA SEMANA</small><b>3 de 5 dias de leitura</b></div><span>60%</span>${progress(60)}</section><button class="primary aurora-button full world-primary-action">Registrar leitura →</button></div>`),
    offline:()=>shell(`<div class="world-screen offline-world-screen">${head('♧','Desafio Sem Tela','Mais presença. Uma vida mais real.')}<section class="world-visual offline-visual"><img src="${A.offline}"><div class="offline-quote">“Desconectar também é um passo para ir mais longe.”</div></section>${stats('5','18 h','4/7')}<section class="world-progress-card"><div><small>META DA SEMANA</small><b>4 de 7 dias offline</b><p>Mais vida no mundo real.</p></div><span>57%</span>${progress(57)}</section><button class="primary aurora-button full world-primary-action">Registrar meu dia offline →</button></div>`),
    tech:()=>shell(`<div class="world-screen rat-world-screen">${head('⚡','Desafio RAT Tech','Treino. Movimento. Evolução.')}<section class="world-visual rat-visual"><div class="world-visual-glow"></div><img src="${A.rat}"><div class="hero-message"><b>Força é constância.</b><span>Seu corpo também merece evolução.</span></div></section>${stats('8','2.430 XP','2/3')}<section class="world-progress-card"><div><small>META DA SEMANA</small><b>2 de 3 dias de treino</b></div><span>67%</span>${progress(67)}</section><section class="mission-link-list daily-missions"><small>MISSÕES DE TREINO</small><article><span>⚔</span><div><b>Complete o treino de hoje</b><small>5–19 min: +15 XP • 20+ min: +30 XP</small></div><i>+</i></article><article><span>🏅</span><div><b>Conquiste a semana</b><small>Treine 3 dias e ganhe +100 XP</small></div><i>›</i></article></section><button class="primary aurora-button full world-primary-action">Registrar meu treino →</button></div>`),
    aqua:()=>shell(`<div class="water-game"><header class="aquaxp-screen-head"><button class="screen-back">‹</button><div><h1><span>💧</span> Desafio da Água</h1><p>Hidratação hoje. Mais conquistas amanhã.</p></div><button class="screen-alert"><span class="avatar">C</span></button></header><section class="aquaxp-status-row"><div><span>🔥</span><b>12</b><small>dias seguidos</small></div><div><span>⚡</span><b>1.250</b><small>XP total</small></div></section><nav class="water-tabs"><button class="active">Mapa</button><button>Missões</button><button>Conquistas</button></nav><section class="adventure-map"><div class="map-atmosphere"></div><img class="map-chalote" src="${A.aqua}"><div class="map-heading"><span>AQUAXP LEAGUE • JORNADA DA SEMANA</span><b>4/7 marcos</b></div><button class="world-node world-1 completed"><span class="world-marker">✓</span><span class="world-copy"><small>MUNDO 1</small><b>Costa da Hidratação</b><em>Concluído</em></span></button><button class="world-node world-2 completed"><span class="world-marker">✓</span><span class="world-copy"><small>MUNDO 2</small><b>Floresta do Equilíbrio</b><em>Concluído</em></span></button><button class="world-node world-3 active"><span class="world-marker">◆</span><span class="world-copy"><small>MUNDO 3</small><b>Ilha da Vitalidade</b><em>4/6 dias</em></span></button><button class="world-node world-4 locked"><span class="world-marker">⌁</span><span class="world-copy"><small>MUNDO 4</small><b>Montanha Gelada</b><em>Bloqueado</em></span></button><div class="map-daily-progress"><span>Meta diária</span><b>2.000 / 2.500 ml</b><em>80%</em>${progress(80)}</div><button class="game-cta aurora">Registrar água →</button></section></div>`),
    achievements:()=>shell(`<div class="achievement-screen">${head('✦','Conquistas por Desafio','Cada hábito abre uma nova relíquia.')}<nav class="world-tabs achievement-tabs"><button>Total</button><button>Água</button><button>RAT Tech</button><button class="active">Leitura</button><button>Sem Tela</button></nav><section class="achievement-summary"><img src="${A.reading}"><div><small>LEITURA</small><b>4/6 conquistas</b>${progress(67)}</div></section><section class="achievement-grid-v3">${['▣|Leitor Iniciante','✦|Meta de Hoje','◇|Viajante de Histórias','🏅|Semana da Leitura','▤|100 Páginas','♛|Mente Aberta'].map((x,i)=>{const [ic,t]=x.split('|');return `<article class="achievement-hex ${i>3?'locked':'unlocked'} ${i===3?'rare':''}"><div class="hex-icon"><span>${i>3?'▣':ic}</span></div><b>${t}</b><small>${i>3?'Continue evoluindo.':'Conquista desbloqueada.'}</small><i>${i>3?'⌁':'✓'}</i></article>`}).join('')}</section><blockquote>“Cada passo conta. Você está evoluindo.”</blockquote></div>`),
    progress:()=>shell(`<div class="total-screen">${head('♜','Progresso Total','Juntos por um amanhã mais saudável.')}<section class="level-shield"><span>NÍVEL 12</span><b>2.450 XP</b><small>550 XP para o nível 13</small>${progress(82)}</section><section class="total-stat-row"><div><span>🔥</span><b>28</b><small>dias seguidos</small></div><div><span>⚔</span><b>42</b><small>missões</small></div><div><span>🏆</span><b>12</b><small>conquistas</small></div></section><section class="contribution-panel"><div class="compact-section-title"><h2>Contribuição por desafio</h2></div>${[['aqua','💧','AquaXP League','42%'],['rat','⚡','RAT Tech','28%'],['reading','▣','Leitura','20%'],['offline','♧','Sem Tela','10%']].map(x=>`<article><span class="contribution-symbol ${x[0]}">${x[1]}</span><div><b>${x[2]}</b><small>Progresso real do desafio</small>${progress(parseInt(x[3]))}</div><em>${x[3]}</em></article>`).join('')}</section><blockquote>“Cada passo conta. Você está fazendo a diferença.”</blockquote></div>`),
    ranking:()=>shell(`<div class="ranking-screen">${head('🏆','Ranking Geral','Todos os exploradores. Um futuro maior.')}<nav class="world-tabs ranking-world-tabs"><button class="active">Geral</button><button>Água</button><button>RAT Tech</button><button>Leitura</button><button>Sem Tela</button></nav><nav class="period-tabs"><button>Esta semana</button><button class="active">Este mês</button><button>Geral</button></nav><section class="ranking-explainer"><span>✦</span><p>O ranking geral soma o XP dos desafios em que cada pessoa participa.</p></section><div class="ranking-columns"><span>#</span><span>EXPLORADOR</span><span>XP</span></div><section class="ranking-list">${['♛|AquaMaster|12.430','♜|LuaTech|11.920','♝|BioNinja|10.880','4|ClaraVibes|9.760','5|EcoRafa|9.420','6|Você|8.350','7|LeituraPro|8.120','8|GabiSolar|7.980','9|MindFlow|7.610','10|TechBalance|7.200'].map((x,i)=>{const [rank,name,xp]=x.split('|');return `<article class="ranking-row ${name==='Você'?'me':''}"><strong>${rank}</strong><div class="ranking-user"><span class="avatar">${name[0]}</span><div><b>${name}</b><small>@${name.toLowerCase()} • ${i%3+2} mundos</small></div></div><span>${xp} XP</span></article>`}).join('')}</section></div>`)
  };
  app.innerHTML=(screens[view]||screens.challenges)();
})();
